# Generated by Django 5.1.4 on 2025-01-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(default=None, max_length=100, null=True)),
                ('server_name', models.TextField(default=None, max_length=100, null=True)),
                ('api_url', models.TextField(default=None, max_length=1000, null=True)),
                ('serer_ip', models.TextField(default=None, max_length=100, null=True)),
                ('server_port', models.TextField(default=None, max_length=100, null=True)),
                ('manager_id', models.TextField(default=None, max_length=100, null=True)),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='master_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_id', models.IntegerField(default=None, null=True)),
                ('name', models.TextField(default=None, max_length=100, null=True)),
                ('commission', models.FloatField(default=False, null=True)),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('set_identical', models.BooleanField(default=False, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.server_details')),
            ],
        ),
        migrations.CreateModel(
            name='copier_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_id', models.IntegerField(default=None, null=True)),
                ('name', models.TextField(default=None, max_length=100, null=True)),
                ('commission', models.FloatField(default=False, null=True)),
                ('risk', models.TextField(default=False, max_length=100, null=True)),
                ('stop_loss', models.BooleanField(default=False, null=True)),
                ('take_profit', models.BooleanField(default=False, null=True)),
                ('reverse_trade', models.BooleanField(default=False, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.master_details')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.server_details')),
            ],
        ),
    ]
