# Generated by Django 5.1.4 on 2025-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copier_details',
            name='password',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_details',
            name='password',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
