# Generated by Django 5.1.4 on 2025-01-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_rename_manager_id_server_details_server_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server_details',
            old_name='serer_ip',
            new_name='server_ip',
        ),
    ]
